<?php
return <<<EOT
.DS_Store*
/.toolkit/
/.toolkit/*
/wp-config.php
/backup/
/backup/*
/deploy/development.yml
/public/index.php
/public/uploads/*
/public/cache/*
/public/themes/index.php
/public/themes/toolkit-*/
/public/themes/toolkit-*/*
/public/themes/twenty*/
/public/themes/twenty*/*
/public/plugins/index.php
/public/plugins/toolkit-*/
/public/plugins/toolkit-*/*
/wordpress/.htaccess
/wordpress/wp-*.php
/wordpress/readme.html
/wordpress/license.txt
/wordpress/index.php
/wordpress/xmlrpc.php
/wordpress/public
/wordpress/wp-admin/
/wordpress/wp-admin/*
/wordpress/wp-includes/
/wordpress/wp-includes/*
/wordpress/wp-content/
/wordpress/wp-content/*
EOT;
?>
